// svelte-web/src/TodoList.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import List from "@smui/list";
  import Textfield from "@smui/textfield";

  import TodoItem from "./TodoItem.svelte";
  import type { TodoItemData } from "./types";
  import { fetchTyped } from "./util";

  let todos: TodoItemData[] = [];
  let newTodoTitle = "";

  onMount(async () => {
    todos = await fetchTyped<TodoItemData[]>("api/todo");
  });

  const handleNewTodoSubmit = async (event) => {
    const newItem = { title: newTodoTitle };
    const response = await fetch("/api/todo", {
      method: "POST",
      body: JSON.stringify(newItem),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const newTodo = await response.json();
    todos = [...todos, newTodo];
    newTodoTitle = "";
  };

  const handleDeleted = (event) => {
    todos = todos.filter((todo) => todo.id != event.detail.id);

    fetch(`/api/todo/${event.detail.id}`, { method: "DELETE" });
  };
</script>

<form on:submit|preventDefault={handleNewTodoSubmit}>
  <Textfield class="new-task" bind:value={newTodoTitle} label="New Task" />
</form>
<List>
  {#each todos as todo}
    <TodoItem {todo} on:deleted={handleDeleted} />
  {/each}
</List>

<style>
  :global(.new-task) {
    width: 95%;
    margin: 0 20px;
  }
</style>

// solid-web/src/TodoList.tsx
import { Component, createEffect, createSignal, For } from "solid-js";
import TodoItem from "./TodoItem";
import { TodoItemData } from "./types";
import { fetchTyped } from "./util";

const TodoList: Component = () => {
  const [todos, setTodos] = createSignal([]);
  const [newItemTitle, setNewItemTitle] = createSignal("");

  createEffect(async () => {
    setTodos(await fetchTyped<TodoItemData[]>("api/todo"));
  });

  const onNewTodoItemSubmit = async (event: Event) => {
    event.preventDefault();

    const response = await fetch("/api/todo", {
      method: "POST",
      body: JSON.stringify({ title: newItemTitle() }),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const newTodo = await response.json();
    setNewItemTitle("");
    setTodos([...todos(), newTodo]);
  };

  const onDelete = async (id: number) => {
    setTodos(todos().filter((item) => item.id != id));
    fetch(`/api/todo/${id}`, { method: "DELETE" });
  };

  return (
    <div>
      <form onSubmit={onNewTodoItemSubmit}>
        <input
          value={newItemTitle()}
          onChange={(event) => setNewItemTitle(event.currentTarget.value)}
          class="border border-neutral-400"
        />
      </form>
      <For each={todos()}>
        {(item) => <TodoItem item={item} onDelete={() => onDelete(item.id)} />}
      </For>
    </div>
  );
};

export default TodoList;
