// svelte-web/src/TodoItem.svelte
<script lang="ts">
  import Checkbox from "@smui/checkbox";
  import { Item, Graphic, Meta, Label } from "@smui/list";

  import type { TodoItemData } from "./types";
  import { createEventDispatcher } from "svelte";

  export let todo: TodoItemData;
  const dispatch = createEventDispatcher();

  const handleToggle = () => {
    todo = { ...todo, completed: !todo.completed };

    fetch(`/api/todo/${todo.id}`, {
      method: "PUT",
      body: JSON.stringify(todo),
      headers: {
        "Content-Type": "application/json",
      },
    });
  };
</script>

<Item on:click={handleToggle}>
  <Checkbox checked={todo.completed} />
  <span class:completed={todo.completed}>
    <Label>{todo.title}</Label>
  </span>
  <Meta>
    <span on:click|stopPropagation={() => dispatch("deleted", { id: todo.id })}>
      <Graphic class="material-icons">delete</Graphic>
    </span>
  </Meta>
</Item>

<style>
  .completed {
    text-decoration: line-through;
  }

  :global(.material-icons) {
    color: #b71c1c;
  }

  :global(.material-icons):hover {
    color: #921616;
  }
</style>

// solid-web/src/TodoItem.tsx
import { Component, createSignal } from "solid-js";
import { TodoItemData } from "./types";
import { IoClose } from "solid-icons/io";

interface Props {
  item: TodoItemData;
  onDelete: () => void;
}

const TodoItem: Component<Props> = ({ item, onDelete }) => {
  const [isCompleted, setIsCompleted] = createSignal(item.completed);

  console.log("rendering item");

  const onCheckboxToggle = () => {
    const newIsCompleted = !isCompleted();
    fetch(`/api/todo/${item.id}`, {
      method: "PUT",
      body: JSON.stringify({ ...item, completed: newIsCompleted }),
      headers: {
        "Content-Type": "application/json",
      },
    });
    setIsCompleted(newIsCompleted);
  };

  return (
    <div class="flex w-52 items-center">
      <label class="grow cursor-pointer">
        <input
          type="checkbox"
          checked={isCompleted()}
          onChange={onCheckboxToggle}
        />{" "}
        <span classList={{ "line-through": isCompleted() }}>{item.title}</span>
      </label>
      <IoClose
        class="inline hover:text-red-500 cursor-pointer"
        onClick={onDelete}
      />
    </div>
  );
};

export default TodoItem;
